### ISSUE TITLE
build error on Mac OS X 10.6.8: ‘for’ loop initial declaration used outside C99 mode

### ISSUE THREAD

**Issue by dliessi** [hughsie/appstream-glib#165]
I got these errors while building appstream-glib on Mac OS X 10.6.8 via MacPorts:
```
:info:build as-app.c: In function ‘as_app_get_format_by_filename’:
:info:build as-app.c:929: error: ‘for’ loop initial declaration used outside C99 mode
:info:build as-app.c: In function ‘as_app_get_format_by_kind’:
:info:build as-app.c:952: error: ‘for’ loop initial declaration used outside C99 mode
:info:build as-app.c: In function ‘as_app_get_require_by_value’:
:info:build as-app.c:1315: error: ‘for’ loop initial declaration used outside C99 mode
[...]
:info:build as-app.c: In function ‘as_app_recalculate_state’:
:info:build as-app.c:2868: error: ‘for’ loop initial declaration used outside C99 mode
:info:build as-app.c: In function ‘as_app_add_format’:
[...]
:info:build as-app.c:2911: error: ‘for’ loop initial declaration used outside C99 mode
```
Probably the loop variable should be initialized like in https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-app.c#L887.

**Comment by hughsie** [comment]
We now require a C99 compiler in various other places too. What compiler are you using? I've got no access to OS-X hardware unfortunately.

**Comment by dliessi** [comment]
```
$ /usr/bin/gcc-4.2 --version
i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666) (dot 3)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ryandesign** [comment]
@hughsie if you require C99 mode, supply the `-std=c99` flag in `CFLAGS` to tell the compiler to use C99 mode. The default compiler on Mac OS X 10.6 (Apple gcc 4.2.1) defaults to C89 mode but supports C99 mode.

According to your change log, you did this for the autotools build in 0.6.7 and for the meson build in 0.7.2. But according to the [MacPorts bug report](https://trac.macports.org/ticket/54042) the reporter was using 0.6.10.

Still, 0.6.13 built successfully on Mac OS X 10.6 through macOS 10.13 on the MacPorts buildbot system, so I assume the problem is resolved.

**Comment by hughsie** [comment]
Thanks @ryandesign -- appreciated.
